language: node_js
node_js:
- '6'
env:
  global:
  - CI=true
  - NODE_ENV=test
  - AWS_REGION=us-west-2
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: npm run build
script: "./scripts/test.sh"

# https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker
