dist: trusty
sudo: false
language: node_js
# Node 6 has a bug that affects some of our unit tests:
# https://github.com/facebook/jest/issues/3152#issuecomment-287496730
node_js:
- '7'
env:
  global:
  - CI=true
  - CXX=g++-5
  - SLS_DEBUG=true
  - LOG_TEST_COVERAGE=true
  - SSL_CERTIFICATE_ARN=arn:aws:acm:us-east-1:167811431063:certificate/fb405a2a-68c1-4fa3-a1d6-d10f3dd19e59
  ########## Test stage ##########
  # Note: Material UI creates different DOM between development
  # and production Node environments, which breaks Jest snapshot tests.
  # https://github.com/mui-org/material-ui/issues/4466#issuecomment-247424816
  # https://github.com/mui-org/material-ui/blob/master/src/utils/callOnce.js#L6
  # This is why we don't run tests in NODE_ENV=production.
  # Material UI 1.x may fix this, at which point we can use the production
  # environment for testing.
  # @material-ui-1-todo
  - TEST_NODE_ENV=test
  - TEST_STAGE=test
  - TEST_AWS_REGION=us-west-2
  - TEST_AWS_ACCOUNT_ID=167811431063
  - TEST_LOG_LEVEL=fatal # Don't log errors during testing. Some errors are expected.
  # Web app
  - TEST_WEBSITE_DOMAIN=test-tab2017.gladly.io # user-visible domain, used in app JS
  - TEST_PUBLIC_PATH=https://test-tab2017.gladly.io/
  - TEST_GRAPHQL_ENDPOINT=test-tab2017.gladly.io/graphql/
  - TEST_FIREBASE_API_KEY=AIzaSyDrGghKLnfOwwaSnPM0unRDXz_4YdorKU4
  - TEST_FIREBASE_AUTH_DOMAIN=dev-tab-for-a-cause.firebaseapp.com
  - TEST_FIREBASE_DATABASE_URL=https://dev-tab-for-a-cause.firebaseio.com
  - TEST_FIREBASE_PROJECT_ID=dev-tab-for-a-cause
  # - TEST_STATIC_FILES_ENDPOINT=https://d3792fnaedwf9j.cloudfront.net
  - TEST_STATIC_FILES_ENDPOINT=//test-tab2017.gladly.io
  - TEST_CLOUDFRONT_DOMAIN_ALIAS=test-tab2017.gladly.io
  - TEST_ADS_ENABLED=false
  # Media
  - TEST_CLOUDFRONT_MEDIA_DOMAIN_ALIAS=test-tab2017-media.gladly.io
  # GraphQL / Lambda
  - TEST_TABLE_NAME_APPENDIX="-test"
  - TEST_LOGGER=sentry
  - TEST_SENTRY_PUBLIC_KEY=55d60901ba254432814cd9015d100959
  - TEST_SENTRY_PROJECT_ID=184604
  - TEST_FIREBASE_CLIENT_EMAIL=firebase-adminsdk-kuncd@dev-tab-for-a-cause.iam.gserviceaccount.com
  # Endpoints
  - TEST_GRAPHQL_PROXY_DOMAIN=lspir87lia.execute-api.us-west-2.amazonaws.com
  - TEST_GRAPHQL_PROXY_PATH=/test
  - TEST_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - TEST_MEDIA_ENDPOINT=https://test-tab2017-media.gladly.io
  # Deployment
  - TEST_WEB_S3_BUCKET_NAME=test-tab2017.gladly.io
  - TEST_MEDIA_S3_BUCKET_NAME=test-tab2017-media.gladly.io
  # Selenium
  - TEST_SELENIUM_DRIVER_TYPE=remote
  - TEST_SELENIUM_HOST=https://test-tab2017.gladly.io
  - TEST_BROWSERSTACK_USER=kevinjennison1
  # Secrets: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, BROWSERSTACK_KEY, SENTRY_PRIVATE_KEY
  - secure: GqAz4Hh4EqMwm6xi5EiEQgZFPiJG1mn1QNXB5gxDTiBD8vpXLszY0GVEZEj9/64gIXpSonSVpZIIgHCBSldd4cgI/A9y1hg0D/Oxx70neFqQQhhFDVgpckmOdhKQSTWZDn+N/lcfzJdPUzQ+re5UuCjb3UCTjyl5z1EwI4hMhGZitML9BuH2iEvT4Vf/cwd079jRF94qZYU35NFP0ySygSjxoiPTNEfMdFdtZMtd+0zucKC3ijtvqeLqbN+KJijmbkxEOaFz0xnlvjgSPLYd7omSPDXmN3G2KuTeOLcY6nBCUOhbX90MCQkv8VvpWrd3pHURT1Hcnb0aW7jZCGP2Tqopkoe4iIGuVzUTH8z8McRK5Oa3ku7ynovRo5kkxAsao4NuLbcC3frAeITTxn9jk4HiyiuX9KU5antL2pK01pGDpWk2sYW7z7ANxkkDLO1TDz5gE1gwVkO3Eaj8+WhP2/sj+u9qRZ8A6ZfyWC+rVjsWiMqWZRz0PvRBc7j4jQ8RVPzOfjA/MQ+Dm2p061atv0/1CeNdqNzo92P2Z2WB7x2CcURSDXy/fVHuZfXz1VWDlYd9mIjTZDD+20cUrlIIcDFoTgQfZsickybKgaDPH4NcLnoP2jZURWvIVd4qIV6DQUp8UU2jn1G9JML7hudRe7n1iA1XeO1MkH9qM3vEvk4=
  - secure: EW2D1Vr0V3w+3Mg0lr6fONG20D+jecDjrhrEJnEWmwVKh08qC7AFJvQO8bG/BH0Vuc9X2cU85JGRe0taQa6WKaRJnczuqIOh8GP7cbxxzKStAE97zzR7l6f+SxxOD4ex1Vywhuz6cBzCjd/97pqlh4PymSDdbxE2Am2+xpZKmZtCvcxFyg3HE4/CybbCvEYj3gx4AuXfkNlh7KC+9ZyMtGVZfSdwJorEdW8jOrynBF5qZiPVfskR9wrOM9mjZvTKKBVyhNGL6XX60/YozzuNP5MBRINX7XFQHnQASSlRAE8ICR8W4M0BtCBzfmKjldEX01NXQH9NBahGovyiog3NRh8YQwm3ShU+WWZVI6Yjl4Nh35Qp0KlRekZBKAhW+MWHiPAq2e5VEV6DlBnLO1DzCrY/z927BfzrhY3wyMPbFgSWqCPZcz9Sz6wPLxb9g7EbuK4GasYHqCCnzubfKzfImk84mHdpfiA0dh0awGw3vKITnAwjjuxACQcERKt6Q2WVEyoiQRyS6plJW3jx1IAHe+M7m6NDCUaHa9W6mvbCNhvyJJySNEHZFpYefUPCCquWUJWArZMfuKrlSTf4KWKrKMOq5v+yoy5dPM91D6CwmokDFtrOcIn6H2uakmWKCREi5iwv+bLpc2cL5XZ4GbjbpxgRD4qMb9buseJ3NDQmHdQ=
  - secure: YM/qYdVY0vUEXkE8HnrP1ihOwnPDqP5mgYL1HcNNLinJ2Jkno1EeGzXFghzckCr87mfJsjgboPw8Xqj9+K5snOkHYZdW5fHQEwxWMWBWtMrhX96j8rN1B48W5qPIa5N+UfLjvGsxjwn3RwMvnZBYS6YZ1Oxzi/PT9sAHACdNgcWMYhASi5WtkD26qZ2mm0VgOSY3xtlPCoKa8GfPXg5c/mdn/LYM6MOT72QWA0xjnIc/YGYWwxLT5cCcFyfY4a9tVl33topZmAyt8uhLL0b+EaYDR+ND9xTaLZQxaW0ftZaQD60rt7ARUKKfTb+tfmB8gekZl/Zjlymw9G6QN+D6zDTmv8RwDW/izHK1galWjmMGeIel8ueNcLkgVhxnIDF7J4hr/d4zaHtl8fq37BnG5Ns/+8LfHQVe5UuX+ODmj4lAxbWqE+dXFCiLmw4t3mgPRGsgGd64G/+mDsZ0RCweP8USLAYfwsk5OlYQocJSMIFyU1///+ykE1RnI+HAV4QqsTnrfM1ZlocJOajlDt3x4s4MVD1TXug8FOodWzVRtIYN/4Bi6m224T1+slZwC1KGbbZKnEgSUQYRTkPPQFjTqE6okkr/5kwTFwOPdBT8QlA56iySfu0CUICOCCy0T4pP/mi83WbL7QSpLUYnVfBdysvv6au+dzn1smsE1M89ppo=
  - secure: X6PhAUEGOu5YkRpFJhpngWQHnH+PexndfgWbXlFV7r9hBZGN/8wKYSV29mCGW7TP1yZpWV5iXNx9APiq5M9ZtFQAz5BIVGRMfOnmcu3ieVbmtEdIoAQYUKb+ueOgqZU5P477VLXdqFsiHOPneLPY6B16YBD/V9LlknuGFsan2S6tqMqxqviLH2VYVUhSqIutkd4UY5V9i1CgWXov3oBs2hJTZMnAfo2yZlj50D1kK9oJHCOaPPxgwCm6cyZVAYFckh6xZrxhNmmsq2Ca5XgOq8rUGh2i+l+3kBFl8y//TqvIw9fu55LewtT1zLjYGbMaosIsLFY53yPSl80lOAXoq0N7pZ/AAUhoqvyClzWGbJGwBx8brkdu3KwaSyDHDqK9S3d0ct4dlZYoJ18wB3ymnYQIWP3bSDYV9bR3wEebXqmb4npydXKLqj8VG8tDenbImCJvbkllyQUvy0R9t4HFD5PQOskabkAtdNZqO9G1XQM2fZBZ0zVQuwptEtd+Amh2h4apTLc7TRTMELHUPQ8bxr7p/AtaPejFvBeeP/4UFAZV0j33zjIva2FD6ZVoZO0x5LNIx/lWs/059/X2veZi7qi7uC2OI5w8MhvgTEmJWmh653iv5aG0axKLlIAwOZHc40+afDb6z+ViwT9inZeAOgn23XJ049ojyHvjj8GzmdU=
  # MIGRATION_ADMIN_KEY
  - secure: ZkoXKB7r+JnUGGmN6Q9WUPO1bj9jkhl3YqnQK0ygsgskDHYmu2n4/36E+PJr6Ixs/oLOvzmrgXwPMwWAmoOuol0bKe7xToW1vxyUAfByH1pTtUPTRlkC3Mc7ReE5lmBjR9PMAVGdgKb2dc2vrc+6/Ao3u20Wp0Le2V/vfphxbBzH4ai3SG77MAxlqV88Zs/3exWzJeHdMe9tqE9hNAsdwJ/tf7Ah/geyT6tsAIb8I6WCVAk92g+4S2vFTqoQyCZ5cuEOJrtHuCWVD3aHAg6koIt/fWR+iLLejmrMfw3ECUXSxvBsEU46f0r4BfSCW3UdACfCKRiTQUOyDimi5lO0YxWg01WCrJ/rj74vAf/hGYTcEY3vxo9B0heaylBZDrePJEdgMAxH7mDEShE11R8cqBZNnzdoZIRW19UnJsUrb1QeQ7Add/t1tgik2hwbFGKT26sIgb0gOqrvUDBr/7s64X5RmL+X+hpu0+ugBGfncvrdoHg8fX3vg2632L0rJnHNgDUGWec96WPVyqvQlUN7+1i2pewxZuLuDRh8tZmm4S3wJMBq2doHGTPO+bNRP6hXQOyvdXsEIRJSBASibLMXTK4l5enx/JrCFmUAvrIFkkzFSRirXt0Mks2DHIV7vSeWE/3ZKa8OsH2X6QlB6foAtEkzAK5owS2LCQaomPEOmtA=
  ########## Dev stage ##########
  - DEV_NODE_ENV=production
  - DEV_STAGE=dev
  - DEV_AWS_REGION=us-west-2
  - DEV_AWS_ACCOUNT_ID=167811431063
  - DEV_LOG_LEVEL=error
  # Web app
  - DEV_WEBSITE_DOMAIN=dev-tab2017.gladly.io  # user-visible domain, used in app JS
  - DEV_PUBLIC_PATH=https://dev-tab2017.gladly.io/
  - DEV_GRAPHQL_ENDPOINT=dev-tab2017.gladly.io/graphql/
  - DEV_FIREBASE_API_KEY=AIzaSyDrGghKLnfOwwaSnPM0unRDXz_4YdorKU4
  - DEV_FIREBASE_AUTH_DOMAIN=dev-tab-for-a-cause.firebaseapp.com
  - DEV_FIREBASE_DATABASE_URL=https://dev-tab-for-a-cause.firebaseio.com
  - DEV_FIREBASE_PROJECT_ID=dev-tab-for-a-cause
  # - DEV_STATIC_FILES_ENDPOINT=https://d2ienu53qrix0k.cloudfront.net
  - DEV_STATIC_FILES_ENDPOINT=//dev-tab2017.gladly.io
  - DEV_CLOUDFRONT_DOMAIN_ALIAS=dev-tab2017.gladly.io
  - DEV_ADS_ENABLED=true
  # Media
  - DEV_CLOUDFRONT_MEDIA_DOMAIN_ALIAS=dev-tab2017-media.gladly.io
  # GraphQL / Lambda
  - DEV_TABLE_NAME_APPENDIX="-dev"
  - DEV_LOGGER=sentry
  - DEV_SENTRY_PUBLIC_KEY=55d60901ba254432814cd9015d100959
  - DEV_SENTRY_PROJECT_ID=184604
  - DEV_FIREBASE_CLIENT_EMAIL=firebase-adminsdk-kuncd@dev-tab-for-a-cause.iam.gserviceaccount.com
  # Endpoints
  - DEV_GRAPHQL_PROXY_DOMAIN=53a9uos12e.execute-api.us-west-2.amazonaws.com
  - DEV_GRAPHQL_PROXY_PATH=/dev
  - DEV_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - DEV_MEDIA_ENDPOINT=https://dev-tab2017-media.gladly.io
  # Deployment
  - DEV_WEB_S3_BUCKET_NAME=dev-tab2017.gladly.io
  - DEV_MEDIA_S3_BUCKET_NAME=dev-tab2017-media.gladly.io
  # Secrets: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, SENTRY_PRIVATE_KEY
  - secure: wuGQ2fZE1nsNPmEuK3EO1/tFPAa7e5o5TjgRJTMofuRQhjGWyuE9E0WaxDBv/AT9v9gGC3I9CdKlDwigZcXBS9BVP6zdUvYSstVU+5dcHdDDaXC77Q3LmqirKUa6px2wF685Eulb+HmGVK7LPXOOC0fbUDeyNZwqOGD6HbgC0zZLHr8QUvcT3H6Y4indW+BWjI9fPQJU0pqO3uOy9VFbUpFlqIsJ1x+oWq+uTZ/5H/NYmqWtIqM/mXmINwgBB2Va7xiffzAP1UkR1fEWlB2sWyBDaID2g7Rz0Kk5zSzeZXCgTPPA96/IjTKs0Ci8zVuCbR6aU34SmToTjUjTE08S1FHg9p5IsvyAbzmXhuiUlZwTpoEoQEIwHETJt8y4pAreLcnBPXCQtYCKKqfeLpD6bCLoKkdzZolakPkGvdRLWEWk4lwB313fCtb9Ht51yl3kXsLqRElyQQDQ4QC9mV6aRxMTT6nmn+GuWAsNuw3toMTkyxXsVWxFiKfXxmEkPE3cq3xVQtjQJdpv0J5KqbfP9y/nzSh6iTNEVVYkOo1nfNVrAli6SqG/6Jcfpc2lqX0l2PCxyILzpeb0H+STxxblJTFY2vunTpENLQ0wpSEzBD+BuQZ3gDPEZl2MND0ciGzB133ZiIyR6E3O/rZOthNeaf7P1NuLcemB8D40fg7z1aE=
  - secure: RoCiVjVN5DITMGjzh5tErnLSqora04G6JD9A0fsbM3gz+zgNFc7bikroVeMl3h3JTyv9ac25dvTCqDO+mo2ceYKeJwEi0FUYFFDccZ0M2bZ1+lQxjftvsRA1dr3R9Lely3RYS6ij5XcDeXXEghwf8JKnbHLdhGde4kNNorXi5b9EnTUSAefE1dmbRHvIykkEnC3LAIJ6T3+aj0LYsTECXHS5d85a/hFvfcMlVx8aaIcuhSrdUyzFxVJAKMYjEdDw5OLZ+Lk7R/yzekRYKUFWDPswnXp3s9CJvYf4PsuHiqviTvg0tyyqO+7KX2uXFUNqiNeCKgqulQVgo7xhjnZhEJEIrhm8lAecKURQDcK2q+qIUK0GcOQ9kmZYPXtgo13WJG2sQavDStxXbbkh8kb/AByJp0NMRE/1kgSu80Sh/E0wE8lK94u5S3ofWZEDtMKnt7pZo8+FwtXPi5+gbOo37EjC/fglCNsTP6Gllr0GmgkOmrNfOMH5IftkhZ+L4r61TsbflM9rrifLkjx5D/BiIP9H3kc86SWpq2ALeeCBK0mZ+wpyvXYWEHTPHmyI2LzriP1qa8aPlDp5Rjw/L1rJZikkLUPZHg+TTIDETQlXAbhW+E8CxB0De3jNE7psaR7FUGY/ueSvMW+Z4xpAdlBRTkbJHDTf3KAdWsmB79IP1JI=
  - secure: N8SoSEmnhULeDYaLVhxJuEc81RfYhSEZmntH9SjTj9IfKbHlY5P6SMueYZH1uFpImj/m1VC1qy1fyULtUDKXVjXtZynQg2/3rnrjvoVP0Jp9Mv0dpbx179jv/M6Q6+WqygM48kSszMjFnnKo4mCMQCdXvfGLYEvktCLU2+4Mza4TxoDTNzWykc+HZcJgTAVUt2Un4wLqR6rUnHIUDMnXnjHPETcw3ndIZFJx0sPQHr144vZid/yF3hwO5u3oNmnSz6Yad19GaYvDbb3Mo6cwz05mycKUQgYrTi9cgtBW1dJqjUA7a2vbaGqc/Pmer/y8vw9pzC8dhkkCYuSv0YJddGC+7DnKHnuzC6iFPWsgbGZiOPdr+m+KRApFALMLH7Y1t08zVdNc0nQrx52oDHVANek90Kv1J5EKAMpB7vWJQVeONua0dhq2QfbO3fdLmf90/r64GVfg30rWbKZkPh9QscFQpJT/fksLzjUHZUYwtWXTW9EK2iituionK71Gn/+YiFi75QBdVO6HOoWFAXQ5DKQnQ1XSwogOUuxk/9CMR9DgBPk+angi1t6Jd5ybrKqpSC/wAZOH/Vc/6N4B0xJrhH2q4ed8zAJXBqPZDRNk64NrkKPULYVlfotIbRCbkPCLKE2ImpZJMPxifKN7SQ3IGwz/KGfKn7NjX56i6cMjxDs=
  # MIGRATION_ADMIN_KEY
  - secure: pR1GDWClMt/p/ouu8uyrryqG2m9QR3ADoUnTlqkrxMeCcOUqIYVV+WyX8ks99RjNiMJTKjB2iEKDOn0BL/ZFhdVhWEW0qzf+ry7j973cZ+qTNGl3iRlUDQ+J1PKYtg004keCLCPr3heIUZtD4Hwf6OzKSOqjvtJjvI7lTCVXM1l1YCg1uzba9zv13tM5bqsUM7zy8hoOMiPSXnSjqjgFFJkYxTIIylXttLPQeItt5VUI4IzADwnVyPQ10jbpfVefHkLCqtW+/nnLK23Dm+nm3+6iNfxPxCCI8AMz7Vg7yUeau2sQElj+CwfczJ+C8GZ1zmQffumAa7fSCq4V3dc4I6QqZ8XnSRXxPodpx/BJxDq4kBYtPYelH/Mf1+WpHcLfUW8J3VFhlEOckJr1PLgFPEkya7jCx3c3C6jSAhIisberS8MJfw5GwG7dnEWAPfxp9dqJg2iPiDECXWfmPVSBY0VDbl0MjLvyxrvxwXRpvW1o7tmIcECLC5F3+sKLE7LPLymOPfJBy9g4Dn/scaKdv7THN3DghOhv8A/i6uW6cFuFRdIwRvm6qlQjdwHuXZoXNNQgON9gcaOdDi61fdjK4cRdy5U6KJcurhjQqim9BWYZuM9F+9co69sXWlSuWvLpXPOlGs8R09ZXaD/X/klM1VQT0VHqBKujXZdrfMbbYIM=
  ########## Production stage ##########
  - PROD_NODE_ENV=production
  - PROD_STAGE=production
  - PROD_AWS_REGION=us-west-2
  - PROD_AWS_ACCOUNT_ID=167811431063
  - PROD_LOG_LEVEL=error
  # Web app
  - PROD_WEBSITE_DOMAIN=tab.gladly.io # user-visible domain, used in app JS
  - PROD_PUBLIC_PATH=https://prod-tab2017.gladly.io/
  - PROD_GRAPHQL_ENDPOINT=tab.gladly.io/graphql/
  - PROD_FIREBASE_API_KEY=AIzaSyDZKbk3DzJwA9nWLlpt6hjqhTm6WY-WOnk
  - PROD_FIREBASE_AUTH_DOMAIN=tab-for-a-cause.firebaseapp.com
  - PROD_FIREBASE_DATABASE_URL=https://tab-for-a-cause.firebaseio.com
  - PROD_FIREBASE_PROJECT_ID=tab-for-a-cause
  # - PROD_STATIC_FILES_ENDPOINT=https://d2dsqma4win6dv.cloudfront.net
  - PROD_STATIC_FILES_ENDPOINT=//tab.gladly.io
  - PROD_CLOUDFRONT_DOMAIN_ALIAS=tab.gladly.io
  - PROD_ADS_ENABLED=true
  # Media
  - PROD_CLOUDFRONT_MEDIA_DOMAIN_ALIAS=prod-tab2017-media.gladly.io
  # GraphQL / Lambda
  - PROD_TABLE_NAME_APPENDIX="-prod"
  - PROD_LOGGER=sentry
  - PROD_SENTRY_PUBLIC_KEY=55d60901ba254432814cd9015d100959
  - PROD_SENTRY_PROJECT_ID=184604
  - PROD_FIREBASE_CLIENT_EMAIL=firebase-adminsdk-mg6w3@tab-for-a-cause.iam.gserviceaccount.com
  # Endpoints
  - PROD_GRAPHQL_PROXY_DOMAIN=qy89x5t2i9.execute-api.us-west-2.amazonaws.com
  - PROD_GRAPHQL_PROXY_PATH=/prod
  - PROD_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - PROD_MEDIA_ENDPOINT=https://prod-tab2017-media.gladly.io
  # Deployment
  - PROD_WEB_S3_BUCKET_NAME=prod-tab2017.gladly.io
  - PROD_MEDIA_S3_BUCKET_NAME=prod-tab2017-media.gladly.io
  # Secrets
  - secure: aHjjaEjCNXRimME1tROAfN/iFbyg9W8Uu+/sQT8gEC0vCsqblFK4/eI9wga0eljO6nhOS68MUTdaFQhBDrRQCum5v3y9tLxBI+XQP1vauXPtFJToh6QeB4bCu0w2dNBzcCXcwew0YP66D7UAMQQx0o9t1UshFSUdVxRvv7s4A9ro1vahD9dZuPy+MJJQPYILmq/svioWi2MgfLQSLWIzck7VCFLgEPwgBati6o/lMIoMiUuUmNQDS68ceUtR2sqWpzj1UiIf0S4YzuzpLKL7YzhsdB7MOvI0nJ9SB5Z/S2E+pHKIVUqS0RjCCzQR+XdoTM/dgrLizjBwt2aKx6ElFzXU2XMimv/50l6I0utnZboT+oR9XrZ65j0gq0zYQWrixJ+aQbbnodJGUAK3ab4+mQG0i+/BA+lTreCmFHLIVglSm55pTIaCT6fDZCKPMqIaf4uZ4XiMDtbW4LUeT4MzRO9b0GtEjdKFeAaBihkv/m8sneHfqWurpNIKBdXEb8G21+dIaxPKxWC6fjDfX0Rhv476d7r+kJYLi4YScRhkBBHQ1BpOj4Fi6XU6gK6+C6sEf4Q//w3xXCHNNDS2ynWgtGTESabSY0Xg8ge6p+KmQCMi6yc8u6fGiFwf5JCgefLKSV7KpICEsEoN8F/tkxUVrVIB084V1iMkvw0z86GMAEc=
  - secure: li6wI7k7TEUJ15KT9vzZEjcJq1nVcGO9gwSXv9vRbktfpztTaRrORc5N5T4/SeHHlURDMr5PxhwB6lYuXIeRhWIh/j48La01HOoMPzhz8qTzK+HaakN/Ebzyx1/mJb28A4JZqpiHiaRWKZopCj5OMGTnZlBUAHFC9dDfgbTXyatn02SwRrAy7tMs0IdmsKnDXGB8zV2LvpxL6b0XenwwZQJ4oI5whWAut9PGhfnB1IWjDlE7TlYC43mEqVHFaHZsEoOf68utVLA6iMHzLja0Lh4SIIDDk0qo99yxt8+EXhiI7WQ4vhPcL42m2/E8QQbiPmRHkrjtSyhN46qAJdzdbju+1krgslruHBXFO9X4qZ4KhGYUl1xzW9KbYbhI0i5mbH5lmaDXf1T9eyLdmeluHee0xO/VkP4WwYQyAQm0T/2C0xAqR59t9aevQpX0ALVUh5eKoVkTVo1TT30b2YBtOkoqdleWMOsguifkV8kTvvCpope8hMRPUzOPJWk1qoPqXoKLhh9Q5PboaQgGpHGEXQ/3RhTra+qkKWDxLPVvfF0Lj4zjOsNkAZTEBn+018BAMl36pU3KYeb6d924n/5bqraTg0rxJk951Kx++YLuRRjuZX1B0JbXOtqjLJQEO+to57vda1pW1fUt18Cc1MWFy87yJUtAxojvcMs1acffxP4=
  - secure: qlZ0YAeyIPNqdc3mNYMuvzpsYidLk4fooBpbEGCyeU9l+9OPzrZDc6Cut5p9g8jk6pw6OuCGd+gdKhgoKh/XoW7S5u1EVfu6Ggmoy3jZJKfouKHVnRsrnFlUj1mnP9Q0qI6IZy8mXeEvJlQUtZ5j2VWt3LfH59iK8sALtkFpbQfmeFYV71AGjKlUFm1F68cKph3qPbbjGgGtrCbprLOHcpzLjEQLBhLl7zSgEE/eubwzeGHJKW1x1iCxrT8rn8ryBJZJRDOPPKZ/dX52VsJjHBxa/WZY0riocs5WYh5imQNGHt2sVrAdWuvXzGlPnDDKKGR3QMAxEUXPaT0Gq4VZz9/Xm6WgDdQRT01XFbztmZfSmQCnajpv2RfCdU0HLdZt0LN5mQGXP+Iekngk3AOJxw7yEfVgMN1xEU0NxGHrTqiXMcXQQDgybM2X7lLo/MiwViyNmKODzKJUoN5mDp5J3ORSGFymQ4y16eltkiWuZcynN2WIeEsKcM+OX8+savK/Rl7htWkdFh+AkBQHXXX8k3LdRDrS7IOPkAjtQQFmGoMMfPTkTyX395BUgpT8c1gvE9eiJC5OkVIyQ1ebNTx8HEcpAUwIRfR12icX6jC+eW+qhaaHW1MKSTCN9vl5o3Ug12RjfLlTFAvAs//XjJrOklyAdbikV8HU7AtHQF24ny4=
  # MIGRATION_ADMIN_KEY
  - secure: ZN3gozo9m9CDszf8TwuXmUESt8m+vomEZTcaHhXd8qUGIQvXkWweuMmtWRosgBPGuKnu+GgmpSaK1af6TY3MUbiaaJuOj4kHZIqm4dGQCV+0Pioa6rv4CcOWxMCQd4LHcrXd2wVdtCGpSiyPHnwLvmCOxyiaajnvi1pkjJbn4yCfhAeMEHBLLHwJMoeEa8hpWuvMTsnon+K3FjBPnOkirxA0kfXg6UjOIqWLfXNlUBBAFwoRS5ufRvoh47JNwoB1ejeNH3zX/D2xFxw4C6+X2epqnvQaxpBlnPqZcGlWd0Lcf1GOAqubWS0XUlYII0RhispzT3fv9cVUJiyT93bkha+PB2IMiVnig30envHNIkTgqCmtIpBGymZ0e7w50B2Ms63K0aF/MlR3fmOhOzyzJycnUUquQaLH3Hf3ExIdz+jhVoSBbrgfIMcu0SCjKt/SReShqLBUX+9O4dfA0ZKdJY7MQ3RDypkA6xmMaMgpRIFoh1uKFqioo3gv/ehMB8Qepj/ZEVmM4F1d+pl2I4bR82nOdcboa58uFTLVxtnBFt1ccFIdwUHs78s+l/wDYz28CQS8+uCaoLtCS6RUYwGTXH24lJcKN94vNETGKiaHqxesbLUr5BKl7kZfrv0za5kxE4VXIV82RUf6XAudz17EJNFZzxaboXDUHIdN3vAjFfc=
before_install:
  # Decrypt amazon-cpm-codes.json
  # Debugging
  - ls ./graphql/database/userRevenue/
  - rm ./graphql/database/userRevenue/amazon-cpm-codes.json
  - ls ./graphql/database/userRevenue/
  - openssl aes-256-cbc -K $encrypted_a337bde16f21_key -iv $encrypted_a337bde16f21_iv
    -in amazon-cpm-codes.json.enc -out ./graphql/database/userRevenue/amazon-cpm-codes.json
    -d
  - ls ./graphql/database/userRevenue/
  # Install Yarn
  # https://yarnpkg.com/en/docs/install-ci#travis-tab
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  # Gulp (used in Prebid.js build)
  - yarn global add gulp
  # AWS CLI
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install: yarn run all:install
script:
  - yarn run ci:test
  # TODO: handle PR restrictions. See:
  # https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
  # TODO: reenable when we start using end-to-end-tests.
  # - yarn run ci:deploy test
  # - yarn run ci:test:integration
# TODO: master branch deploy to prod; other logic for test/dev
# Note: travis_wait doesn't work well in deploy:
#   https://github.com/travis-ci/travis-ci/issues/7961
deploy:
  # Dev stage deploy
  - provider: script
    script: yarn run ci:deploy dev
    on:
      # TODO: revert to master branch only
      all_branches: true
      # branch: master
    # don't reset working directory after script step
    skip_cleanup: true
  # Prod stage deploy
  - provider: script
    script: yarn run ci:deploy prod
    on:
      branch: master
    skip_cleanup: true
cache: yarn
