language: node_js
node_js:
- '6'
env:
  global:
  - CI=true
  ########## Test stage ##########
  - TEST_NODE_ENV=production
  - TEST_AWS_REGION=us-west-2
  # AWS Cognito
  - TEST_COGNITO_REGION=us-west-2
  - TEST_COGNITO_IDENTITYPOOLID=arn:aws:cognito-idp:us-west-2:123456789:userpool/us-west-2_abcdefghi
  - TEST_COGNITO_USERPOOLID=us-west-2_abcdefghi
  - TEST_COGNITO_CLIENTID=abc123def456ghi789
  # Web app
  - TEST_PUBLIC_PATH=/
  - TEST_WEB_HOST=localhost
  - TEST_WEB_PORT=3000
  # GraphQL
  - TEST_TABLE_NAME_APPENDIX=""
  - TEST_GRAPHQL_PORT=8080
  # Endpoints
  - TEST_GRAPHQL_ENDPOINT=http://localhost:8080
  - TEST_DYNAMODB_ENDPOINT=http://localhost:8000
  - TEST_S3_ENDPOINT=http://localhost:9000
  # Secrets
  - secure: GqAz4Hh4EqMwm6xi5EiEQgZFPiJG1mn1QNXB5gxDTiBD8vpXLszY0GVEZEj9/64gIXpSonSVpZIIgHCBSldd4cgI/A9y1hg0D/Oxx70neFqQQhhFDVgpckmOdhKQSTWZDn+N/lcfzJdPUzQ+re5UuCjb3UCTjyl5z1EwI4hMhGZitML9BuH2iEvT4Vf/cwd079jRF94qZYU35NFP0ySygSjxoiPTNEfMdFdtZMtd+0zucKC3ijtvqeLqbN+KJijmbkxEOaFz0xnlvjgSPLYd7omSPDXmN3G2KuTeOLcY6nBCUOhbX90MCQkv8VvpWrd3pHURT1Hcnb0aW7jZCGP2Tqopkoe4iIGuVzUTH8z8McRK5Oa3ku7ynovRo5kkxAsao4NuLbcC3frAeITTxn9jk4HiyiuX9KU5antL2pK01pGDpWk2sYW7z7ANxkkDLO1TDz5gE1gwVkO3Eaj8+WhP2/sj+u9qRZ8A6ZfyWC+rVjsWiMqWZRz0PvRBc7j4jQ8RVPzOfjA/MQ+Dm2p061atv0/1CeNdqNzo92P2Z2WB7x2CcURSDXy/fVHuZfXz1VWDlYd9mIjTZDD+20cUrlIIcDFoTgQfZsickybKgaDPH4NcLnoP2jZURWvIVd4qIV6DQUp8UU2jn1G9JML7hudRe7n1iA1XeO1MkH9qM3vEvk4=
  - secure: pEf7L3oV50fcgH7yA2uOpC+EIINV/1zxhA8+fZTj49bwvX9Uue4ZSKi1CqxWBz5gG6aKMfrc/WVDr6RiUmVralPQ2zhnuObJz6ed5nEJD+fkfmiOfeNltWOzl0mo29m6BU95cd4HcYauO2ON7BevHVjGSlZD2/z4GicfGsCC7vQ4QlvNCRmKsU3GkM57oBRH0dkkIhv5a7kia1wHHJuOx42/bHddCui1+pUC72mQMWxsiID7ezswIBgFqE7KjI+HZ5V6P7QXA9IS5iuIsYG5zrQAfacrHXSb0oszHj9KHBdKPr27k3/3R+7uA77Voc4hUBFVQtWlk9V45WTOnPyBX9gLXJ+MuFoEi1QHPenKu3aEwMeJ7cVv+pIXGVwwte4Yt5xwhMM8WK1hf4NlPdJbe5BsjhZ4PDakBgp0QWjyqU0+qzpDDJ0VtRaR3fQH5G/g9nZ1FwzEA37G9/0wSLqnO7/NeH3Y1nh5H/2AZ+1ysoTvg5k73rebc9tlzqxjGypLqgsqJfs5ldqQkrptbNBjkCU3+C8cQkAMLyBsRc61cGKlAuRfzNwdTwQfMZ5mqBM9thFevU9g2t6TlV8dVfVO2iC+axEArtoaRdeiAcgX6/UI7ZbLrzlKBRY5X/0gALdAHRDLuMnBYJko9+4y8OeHfT07MjbIlWBiOEyTzSPHpr8=
  ########## Dev stage ##########
  - DEV_NODE_ENV=production
  - DEV_AWS_REGION=us-west-2
  # AWS Cognito
  - DEV_COGNITO_REGION=us-west-2
  - DEV_COGNITO_IDENTITYPOOLID=arn:aws:cognito-idp:us-west-2:167811431063:userpool/us-west-2_9MWuEqLeW
  - DEV_COGNITO_USERPOOLID=us-west-2_9MWuEqLeW
  - DEV_COGNITO_CLIENTID=5d08amkokqkkd16ofvt7lisk6c
  # Web app
  - DEV_PUBLIC_PATH=http://dev-tab2017.gladly.io/
  # GraphQL
  - DEV_TABLE_NAME_APPENDIX="-dev"
  # Endpoints
  - DEV_GRAPHQL_ENDPOINT=https://53a9uos12e.execute-api.us-west-2.amazonaws.com/dev/graphql
  - DEV_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - DEV_S3_ENDPOINT=https://s3-us-west-2.amazonaws.com/dev-tab2017-media.gladly.io
  # Secrets
  - secure: wuGQ2fZE1nsNPmEuK3EO1/tFPAa7e5o5TjgRJTMofuRQhjGWyuE9E0WaxDBv/AT9v9gGC3I9CdKlDwigZcXBS9BVP6zdUvYSstVU+5dcHdDDaXC77Q3LmqirKUa6px2wF685Eulb+HmGVK7LPXOOC0fbUDeyNZwqOGD6HbgC0zZLHr8QUvcT3H6Y4indW+BWjI9fPQJU0pqO3uOy9VFbUpFlqIsJ1x+oWq+uTZ/5H/NYmqWtIqM/mXmINwgBB2Va7xiffzAP1UkR1fEWlB2sWyBDaID2g7Rz0Kk5zSzeZXCgTPPA96/IjTKs0Ci8zVuCbR6aU34SmToTjUjTE08S1FHg9p5IsvyAbzmXhuiUlZwTpoEoQEIwHETJt8y4pAreLcnBPXCQtYCKKqfeLpD6bCLoKkdzZolakPkGvdRLWEWk4lwB313fCtb9Ht51yl3kXsLqRElyQQDQ4QC9mV6aRxMTT6nmn+GuWAsNuw3toMTkyxXsVWxFiKfXxmEkPE3cq3xVQtjQJdpv0J5KqbfP9y/nzSh6iTNEVVYkOo1nfNVrAli6SqG/6Jcfpc2lqX0l2PCxyILzpeb0H+STxxblJTFY2vunTpENLQ0wpSEzBD+BuQZ3gDPEZl2MND0ciGzB133ZiIyR6E3O/rZOthNeaf7P1NuLcemB8D40fg7z1aE=
  - secure: KiqJmugOh2stQL9Y4myDHTv/aae0hiyDhZ8R9TwLcAWjICsLhj1aWuNog2/YCP8k1yiOIvjsq/RXxeQhb8AP9mJvfhqn1pThqAaw2b62NLwTxZrJUn3AM5P+I6ndC8woD1almqADaWZtl9Z9xqj5fsjM6fCxJsNURoPA4KBmtbNznhcnEB1iisbdU05EpC4osdoXmFuTTMSP8DF/TUhNj/hCl67++UFqiNo0gleRKhS9EsqpqPLhLXJ6ecNm93mWIXEgGRd264e5hRQskPJqgwW3XQO7Vzd8jSvYFM+GUmUhaP64U4ZiakFx52d7wlcPakhmWSukJRPIqed8mEgUWwF2YCs+j2dAZ82QiiphNtM/A+KuAF3OPAIxkV0GKe8rtajFMNJE8OhKCRuQzGmYqi3hGXFXpL73jJNqnc5au7Jp8vVYg2fY4Rtq+BMSQjlz6Q7HQ/tJHzILdhnJ0PjEGFX66q6G/kBXHMf+xETcPIeT7MSxwnmXU1rJKa+pT+e2YsABiBDxBs6xKqj0KkJF6nltiagzL4qTDwnp2c5FGRRPpRsXI51WT30kswLQLYkT8NDKLZOeK8cAYF1RX83FoeYPKMAhh5CNca/xNHSyx+CYVdspvUdQ+bk3UZXCTytAMVO78asgaOLHHKzWRqCfc/PVDFpatU6ybnnvMBNPJrU=
  ########## TODO: production stage ##########
  - secure: aHjjaEjCNXRimME1tROAfN/iFbyg9W8Uu+/sQT8gEC0vCsqblFK4/eI9wga0eljO6nhOS68MUTdaFQhBDrRQCum5v3y9tLxBI+XQP1vauXPtFJToh6QeB4bCu0w2dNBzcCXcwew0YP66D7UAMQQx0o9t1UshFSUdVxRvv7s4A9ro1vahD9dZuPy+MJJQPYILmq/svioWi2MgfLQSLWIzck7VCFLgEPwgBati6o/lMIoMiUuUmNQDS68ceUtR2sqWpzj1UiIf0S4YzuzpLKL7YzhsdB7MOvI0nJ9SB5Z/S2E+pHKIVUqS0RjCCzQR+XdoTM/dgrLizjBwt2aKx6ElFzXU2XMimv/50l6I0utnZboT+oR9XrZ65j0gq0zYQWrixJ+aQbbnodJGUAK3ab4+mQG0i+/BA+lTreCmFHLIVglSm55pTIaCT6fDZCKPMqIaf4uZ4XiMDtbW4LUeT4MzRO9b0GtEjdKFeAaBihkv/m8sneHfqWurpNIKBdXEb8G21+dIaxPKxWC6fjDfX0Rhv476d7r+kJYLi4YScRhkBBHQ1BpOj4Fi6XU6gK6+C6sEf4Q//w3xXCHNNDS2ynWgtGTESabSY0Xg8ge6p+KmQCMi6yc8u6fGiFwf5JCgefLKSV7KpICEsEoN8F/tkxUVrVIB084V1iMkvw0z86GMAEc=
  - secure: St6quR8XU0wlh8uLbZH/C+uT3PFDlLpVNNQDOAZudl0Ta2xEQgKXeTSMIuvhpbvweUibrmq5Qv+3pxEpi0vw/OlYO1CfQ0AkqrVi0BUbs1Iejedz1hYVeHuKl/CiaV5fiP93hbGvX/ktRG2eg82+RBz4VnBy2+xE8kRAjaBvkZYumJoEjsJiQ1DZQJPQ+j1ZOS67x2dmZwOI6mCATGUcQj83X1txWlb+GOgj5WiNFhVTskx6budJ9UIipjPuGN/j8KMA53tWwMMMXWMNQfzJ1G+x2V8Vh7zM2bhR4oZ3YpqbScaiqXRvcOd/KNd5Qd/lxs0mopldmd4ZBE+7F4Sc7kjxkcsypQH+6c9vS6oMNrH+ZekkFWaPktQV1QMAO+KpaCj4h4ZbSOrAy+XMQOL44vLc24xBuEUQKOT7MOEc4rL9MzfOdcs3i9xaJu+OhIEzHdNovxoMPoPcesc76CuKNnz7KIgHQACmrQqZ8Y7jL5Hx2V0TI72xrQ0bcK5ARGIyBK6v6L/1YI2HjALma/LPL/yVxxy/g82pyiWxyTCARH0P9x4bCx9LinXZ5NaG+IvZBxaglJdZv81cv8SQA62bQeEaC8Qq0CiuIVrlJhyhca972l0t0eal02H9SC6bA9m05tV7UqkEn3qVnO6JZloZpANYg3espGTa2m5rSMnOSno=
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=0.22.0-1
install: yarn run all:install
script: yarn run ci:test
deploy:
  provider: script
  script: yarn run ci:deploy dev
  on:
    all_branches: true
cache: yarn
