language: node_js
# Node 6 has a bug that affects some of our unit tests:
# https://github.com/facebook/jest/issues/3152#issuecomment-287496730
node_js:
- '7'
env:
  global:
  - CI=true
  - CXX=g++-5
  - SLS_DEBUG=true
  - LOG_TEST_COVERAGE=true
  ########## Test stage ##########
  - TEST_NODE_ENV=production
  - TEST_AWS_REGION=us-west-2
  - TEST_AWS_ACCOUNT_ID=167811431063
  - TEST_LOG_LEVEL=warn
  # AWS Cognito
  - TEST_COGNITO_REGION=us-west-2
  - TEST_COGNITO_IDENTITYPOOLID=arn:aws:cognito-idp:us-west-2:167811431063:userpool/us-west-2_CtxIyCf3s
  - TEST_COGNITO_USERPOOLID=us-west-2_CtxIyCf3s
  - TEST_COGNITO_CLIENTID=u1vckhq1ba7oarrhu8ksvn9r7
  - TEST_MOCK_DEV_AUTHENTICATION=false
  # Web app
  - TEST_PUBLIC_PATH=http://test-tab2017.gladly.io/
  - TEST_ADS_ENABLED=false
  # GraphQL
  - TEST_TABLE_NAME_APPENDIX="-test"
  - TEST_DEVELOPMENT_LOGGING_ENABLED=0
  # Endpoints
  - TEST_GRAPHQL_ENDPOINT=https://lspir87lia.execute-api.us-west-2.amazonaws.com/test/graphql
  - TEST_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - TEST_S3_ENDPOINT=https://s3-us-west-2.amazonaws.com/test-tab2017-media.gladly.io
  # Deployment
  - TEST_WEB_S3_BUCKET_NAME=test-tab2017.gladly.io
  - TEST_MEDIA_S3_BUCKET_NAME=test-tab2017-media.gladly.io
  # Selenium
  - TEST_SELENIUM_DRIVER_TYPE=remote
  - TEST_SELENIUM_HOST=http://test-tab2017.gladly.io
  - TEST_BROWSERSTACK_USER=kevinjennison1
  # Secrets: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, BROWSERSTACK_KEY 
  - secure: GqAz4Hh4EqMwm6xi5EiEQgZFPiJG1mn1QNXB5gxDTiBD8vpXLszY0GVEZEj9/64gIXpSonSVpZIIgHCBSldd4cgI/A9y1hg0D/Oxx70neFqQQhhFDVgpckmOdhKQSTWZDn+N/lcfzJdPUzQ+re5UuCjb3UCTjyl5z1EwI4hMhGZitML9BuH2iEvT4Vf/cwd079jRF94qZYU35NFP0ySygSjxoiPTNEfMdFdtZMtd+0zucKC3ijtvqeLqbN+KJijmbkxEOaFz0xnlvjgSPLYd7omSPDXmN3G2KuTeOLcY6nBCUOhbX90MCQkv8VvpWrd3pHURT1Hcnb0aW7jZCGP2Tqopkoe4iIGuVzUTH8z8McRK5Oa3ku7ynovRo5kkxAsao4NuLbcC3frAeITTxn9jk4HiyiuX9KU5antL2pK01pGDpWk2sYW7z7ANxkkDLO1TDz5gE1gwVkO3Eaj8+WhP2/sj+u9qRZ8A6ZfyWC+rVjsWiMqWZRz0PvRBc7j4jQ8RVPzOfjA/MQ+Dm2p061atv0/1CeNdqNzo92P2Z2WB7x2CcURSDXy/fVHuZfXz1VWDlYd9mIjTZDD+20cUrlIIcDFoTgQfZsickybKgaDPH4NcLnoP2jZURWvIVd4qIV6DQUp8UU2jn1G9JML7hudRe7n1iA1XeO1MkH9qM3vEvk4=
  - secure: EW2D1Vr0V3w+3Mg0lr6fONG20D+jecDjrhrEJnEWmwVKh08qC7AFJvQO8bG/BH0Vuc9X2cU85JGRe0taQa6WKaRJnczuqIOh8GP7cbxxzKStAE97zzR7l6f+SxxOD4ex1Vywhuz6cBzCjd/97pqlh4PymSDdbxE2Am2+xpZKmZtCvcxFyg3HE4/CybbCvEYj3gx4AuXfkNlh7KC+9ZyMtGVZfSdwJorEdW8jOrynBF5qZiPVfskR9wrOM9mjZvTKKBVyhNGL6XX60/YozzuNP5MBRINX7XFQHnQASSlRAE8ICR8W4M0BtCBzfmKjldEX01NXQH9NBahGovyiog3NRh8YQwm3ShU+WWZVI6Yjl4Nh35Qp0KlRekZBKAhW+MWHiPAq2e5VEV6DlBnLO1DzCrY/z927BfzrhY3wyMPbFgSWqCPZcz9Sz6wPLxb9g7EbuK4GasYHqCCnzubfKzfImk84mHdpfiA0dh0awGw3vKITnAwjjuxACQcERKt6Q2WVEyoiQRyS6plJW3jx1IAHe+M7m6NDCUaHa9W6mvbCNhvyJJySNEHZFpYefUPCCquWUJWArZMfuKrlSTf4KWKrKMOq5v+yoy5dPM91D6CwmokDFtrOcIn6H2uakmWKCREi5iwv+bLpc2cL5XZ4GbjbpxgRD4qMb9buseJ3NDQmHdQ=
  - secure: YM/qYdVY0vUEXkE8HnrP1ihOwnPDqP5mgYL1HcNNLinJ2Jkno1EeGzXFghzckCr87mfJsjgboPw8Xqj9+K5snOkHYZdW5fHQEwxWMWBWtMrhX96j8rN1B48W5qPIa5N+UfLjvGsxjwn3RwMvnZBYS6YZ1Oxzi/PT9sAHACdNgcWMYhASi5WtkD26qZ2mm0VgOSY3xtlPCoKa8GfPXg5c/mdn/LYM6MOT72QWA0xjnIc/YGYWwxLT5cCcFyfY4a9tVl33topZmAyt8uhLL0b+EaYDR+ND9xTaLZQxaW0ftZaQD60rt7ARUKKfTb+tfmB8gekZl/Zjlymw9G6QN+D6zDTmv8RwDW/izHK1galWjmMGeIel8ueNcLkgVhxnIDF7J4hr/d4zaHtl8fq37BnG5Ns/+8LfHQVe5UuX+ODmj4lAxbWqE+dXFCiLmw4t3mgPRGsgGd64G/+mDsZ0RCweP8USLAYfwsk5OlYQocJSMIFyU1///+ykE1RnI+HAV4QqsTnrfM1ZlocJOajlDt3x4s4MVD1TXug8FOodWzVRtIYN/4Bi6m224T1+slZwC1KGbbZKnEgSUQYRTkPPQFjTqE6okkr/5kwTFwOPdBT8QlA56iySfu0CUICOCCy0T4pP/mi83WbL7QSpLUYnVfBdysvv6au+dzn1smsE1M89ppo=
  ########## Dev stage ##########
  - DEV_NODE_ENV=production
  - DEV_AWS_REGION=us-west-2
  - DEV_AWS_ACCOUNT_ID=167811431063
  - TEST_LOG_LEVEL=error
  # AWS Cognito
  - DEV_COGNITO_REGION=us-west-2
  - DEV_COGNITO_IDENTITYPOOLID=arn:aws:cognito-idp:us-west-2:167811431063:userpool/us-west-2_zu5kEM34P
  - DEV_COGNITO_USERPOOLID=us-west-2_zu5kEM34P
  - DEV_COGNITO_CLIENTID=32lj6balg8t2d1209sb50t1m8b
  - DEV_MOCK_DEV_AUTHENTICATION=false
  # Web app
  - DEV_PUBLIC_PATH=http://dev-tab2017.gladly.io/
  - DEV_ADS_ENABLED=true
  # GraphQL
  - DEV_TABLE_NAME_APPENDIX="-dev"
  - DEV_DEVELOPMENT_LOGGING_ENABLED=0
  # Endpoints
  - DEV_GRAPHQL_ENDPOINT=https://53a9uos12e.execute-api.us-west-2.amazonaws.com/dev/graphql
  - DEV_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - DEV_S3_ENDPOINT=https://s3-us-west-2.amazonaws.com/dev-tab2017-media.gladly.io
  # Deployment
  - DEV_WEB_S3_BUCKET_NAME=dev-tab2017.gladly.io
  - DEV_MEDIA_S3_BUCKET_NAME=dev-tab2017-media.gladly.io
  # Secrets
  - secure: wuGQ2fZE1nsNPmEuK3EO1/tFPAa7e5o5TjgRJTMofuRQhjGWyuE9E0WaxDBv/AT9v9gGC3I9CdKlDwigZcXBS9BVP6zdUvYSstVU+5dcHdDDaXC77Q3LmqirKUa6px2wF685Eulb+HmGVK7LPXOOC0fbUDeyNZwqOGD6HbgC0zZLHr8QUvcT3H6Y4indW+BWjI9fPQJU0pqO3uOy9VFbUpFlqIsJ1x+oWq+uTZ/5H/NYmqWtIqM/mXmINwgBB2Va7xiffzAP1UkR1fEWlB2sWyBDaID2g7Rz0Kk5zSzeZXCgTPPA96/IjTKs0Ci8zVuCbR6aU34SmToTjUjTE08S1FHg9p5IsvyAbzmXhuiUlZwTpoEoQEIwHETJt8y4pAreLcnBPXCQtYCKKqfeLpD6bCLoKkdzZolakPkGvdRLWEWk4lwB313fCtb9Ht51yl3kXsLqRElyQQDQ4QC9mV6aRxMTT6nmn+GuWAsNuw3toMTkyxXsVWxFiKfXxmEkPE3cq3xVQtjQJdpv0J5KqbfP9y/nzSh6iTNEVVYkOo1nfNVrAli6SqG/6Jcfpc2lqX0l2PCxyILzpeb0H+STxxblJTFY2vunTpENLQ0wpSEzBD+BuQZ3gDPEZl2MND0ciGzB133ZiIyR6E3O/rZOthNeaf7P1NuLcemB8D40fg7z1aE=
  - secure: RoCiVjVN5DITMGjzh5tErnLSqora04G6JD9A0fsbM3gz+zgNFc7bikroVeMl3h3JTyv9ac25dvTCqDO+mo2ceYKeJwEi0FUYFFDccZ0M2bZ1+lQxjftvsRA1dr3R9Lely3RYS6ij5XcDeXXEghwf8JKnbHLdhGde4kNNorXi5b9EnTUSAefE1dmbRHvIykkEnC3LAIJ6T3+aj0LYsTECXHS5d85a/hFvfcMlVx8aaIcuhSrdUyzFxVJAKMYjEdDw5OLZ+Lk7R/yzekRYKUFWDPswnXp3s9CJvYf4PsuHiqviTvg0tyyqO+7KX2uXFUNqiNeCKgqulQVgo7xhjnZhEJEIrhm8lAecKURQDcK2q+qIUK0GcOQ9kmZYPXtgo13WJG2sQavDStxXbbkh8kb/AByJp0NMRE/1kgSu80Sh/E0wE8lK94u5S3ofWZEDtMKnt7pZo8+FwtXPi5+gbOo37EjC/fglCNsTP6Gllr0GmgkOmrNfOMH5IftkhZ+L4r61TsbflM9rrifLkjx5D/BiIP9H3kc86SWpq2ALeeCBK0mZ+wpyvXYWEHTPHmyI2LzriP1qa8aPlDp5Rjw/L1rJZikkLUPZHg+TTIDETQlXAbhW+E8CxB0De3jNE7psaR7FUGY/ueSvMW+Z4xpAdlBRTkbJHDTf3KAdWsmB79IP1JI=
  ########## Production stage ##########
  - PROD_NODE_ENV=production
  - PROD_AWS_REGION=us-west-2
  - PROD_AWS_ACCOUNT_ID=167811431063
  - PROD_LOG_LEVEL=error
  # AWS Cognito
  - PROD_COGNITO_REGION=us-west-2
  - PROD_COGNITO_IDENTITYPOOLID=arn:aws:cognito-idp:us-west-2:167811431063:userpool/us-west-2_VdpaaoTpR
  - PROD_COGNITO_USERPOOLID=us-west-2_VdpaaoTpR
  - PROD_COGNITO_CLIENTID=7n2os99obf201gk6qi8nca6bp5
  - PROD_MOCK_DEV_AUTHENTICATION=false
  # Web app
  - PROD_PUBLIC_PATH=http://prod-tab2017.gladly.io/
  - PROD_ADS_ENABLED=true
  # GraphQL
  - PROD_TABLE_NAME_APPENDIX="-prod"
  - PROD_DEVELOPMENT_LOGGING_ENABLED=0
  # Endpoints
  - PROD_GRAPHQL_ENDPOINT=https://qy89x5t2i9.execute-api.us-west-2.amazonaws.com/prod/graphql
  - PROD_DYNAMODB_ENDPOINT=dynamodb.us-west-2.amazonaws.com
  - PROD_S3_ENDPOINT=https://s3-us-west-2.amazonaws.com/prod-tab2017-media.gladly.io
  # Deployment
  - PROD_WEB_S3_BUCKET_NAME=prod-tab2017.gladly.io
  - PROD_MEDIA_S3_BUCKET_NAME=prod-tab2017-media.gladly.io
  # Secrets
  - secure: aHjjaEjCNXRimME1tROAfN/iFbyg9W8Uu+/sQT8gEC0vCsqblFK4/eI9wga0eljO6nhOS68MUTdaFQhBDrRQCum5v3y9tLxBI+XQP1vauXPtFJToh6QeB4bCu0w2dNBzcCXcwew0YP66D7UAMQQx0o9t1UshFSUdVxRvv7s4A9ro1vahD9dZuPy+MJJQPYILmq/svioWi2MgfLQSLWIzck7VCFLgEPwgBati6o/lMIoMiUuUmNQDS68ceUtR2sqWpzj1UiIf0S4YzuzpLKL7YzhsdB7MOvI0nJ9SB5Z/S2E+pHKIVUqS0RjCCzQR+XdoTM/dgrLizjBwt2aKx6ElFzXU2XMimv/50l6I0utnZboT+oR9XrZ65j0gq0zYQWrixJ+aQbbnodJGUAK3ab4+mQG0i+/BA+lTreCmFHLIVglSm55pTIaCT6fDZCKPMqIaf4uZ4XiMDtbW4LUeT4MzRO9b0GtEjdKFeAaBihkv/m8sneHfqWurpNIKBdXEb8G21+dIaxPKxWC6fjDfX0Rhv476d7r+kJYLi4YScRhkBBHQ1BpOj4Fi6XU6gK6+C6sEf4Q//w3xXCHNNDS2ynWgtGTESabSY0Xg8ge6p+KmQCMi6yc8u6fGiFwf5JCgefLKSV7KpICEsEoN8F/tkxUVrVIB084V1iMkvw0z86GMAEc=
  - secure: li6wI7k7TEUJ15KT9vzZEjcJq1nVcGO9gwSXv9vRbktfpztTaRrORc5N5T4/SeHHlURDMr5PxhwB6lYuXIeRhWIh/j48La01HOoMPzhz8qTzK+HaakN/Ebzyx1/mJb28A4JZqpiHiaRWKZopCj5OMGTnZlBUAHFC9dDfgbTXyatn02SwRrAy7tMs0IdmsKnDXGB8zV2LvpxL6b0XenwwZQJ4oI5whWAut9PGhfnB1IWjDlE7TlYC43mEqVHFaHZsEoOf68utVLA6iMHzLja0Lh4SIIDDk0qo99yxt8+EXhiI7WQ4vhPcL42m2/E8QQbiPmRHkrjtSyhN46qAJdzdbju+1krgslruHBXFO9X4qZ4KhGYUl1xzW9KbYbhI0i5mbH5lmaDXf1T9eyLdmeluHee0xO/VkP4WwYQyAQm0T/2C0xAqR59t9aevQpX0ALVUh5eKoVkTVo1TT30b2YBtOkoqdleWMOsguifkV8kTvvCpope8hMRPUzOPJWk1qoPqXoKLhh9Q5PboaQgGpHGEXQ/3RhTra+qkKWDxLPVvfF0Lj4zjOsNkAZTEBn+018BAMl36pU3KYeb6d924n/5bqraTg0rxJk951Kx++YLuRRjuZX1B0JbXOtqjLJQEO+to57vda1pW1fUt18Cc1MWFy87yJUtAxojvcMs1acffxP4=
addons:
  # For node-gyp:
  # https://github.com/nodejs/node-gyp#on-unix
  # https://stackoverflow.com/a/40802733/1332513
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5  
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=0.22.0-1
  # Gulp (used in Prebid.js build)
  - yarn global add gulp
  # AWS CLI
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  # Install Watchman for relay-compiler. Remove when fixed:
  # https://github.com/facebook/relay/issues/1644
  - git clone https://github.com/facebook/watchman.git
  - cd watchman
  - git checkout v4.7.0  # the latest stable release
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  # https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch
  - echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
  - echo 999999 | sudo tee -a  /proc/sys/fs/inotify/max_queued_events
  - echo 999999 | sudo tee  -a /proc/sys/fs/inotify/max_user_instances
  - watchman watch-del-all
  - watchman shutdown-server
  - cd ../
  # End Watchman install.
install: yarn run all:install
script:
  - yarn run ci:test
  # TODO: handle PR restrictions. See:
  # https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
  - yarn run ci:deploy test
  - yarn run ci:test:integration
# TODO: master branch deploy to prod; other logic for test/dev
deploy:
  # Dev stage deploy
  - provider: script
    script: yarn run ci:deploy dev
    on:
      # TODO: revert to master branch only
      all_branches: true
      # branch: master
    # don't reset working directory after script step
    skip_cleanup: true
  # Prod stage deploy
  - provider: script
    script: yarn run ci:deploy prod
    # TODO: master only after setup
    on:
      all_branches: true
      # branch: master
    skip_cleanup: true
cache: yarn
