
version: '2'
services:

  dynamodb:
    restart: always
    build:
      context: ./dynamodb/
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/dynamodb
      - ./dynamodb/node_modules:/dynamodb/node_modules
