
version: '2'
services:
  web:
    restart: always
    build:
      context: ./web/
    links:
      - graphql:graphql
    ports:
      - "80:3000"
    volumes:
      - ./web:/web
      - ./web/node_modules:/web/node_modules # http://stackoverflow.com/a/32785014/1332513
    command: ["npm", "start"]

  graphql:
    restart: always
    build:
      context: ./graphql/
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./graphql:/graphql
      - ./graphql/node_modules:/graphql/node_modules
    # command: ["npm", "run", "update-schema", "&&", "npm", "start"]
    command: ["npm", "start"]

  dynamodb:
    restart: always
    build:
      context: ./dynamodb/
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/dynamodb
      - ./dynamodb/node_modules:/dynamodb/node_modules

  lambda:
    restart: always
    build:
      context: ./lambda/
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - ./lambda:/lambda
      - ./lambda/node_modules:/lambda/node_modules

