
version: '2'
services:
  web:
    restart: always
    build:
      context: ./web/
    ports:
      - "80:3000"
    volumes:
      - ./web:/web
      - ./web/node_modules:/web/node_modules # http://stackoverflow.com/a/32785014/1332513
    command: ["npm", "start"]
