# TODO: delete service if switch to Firebase auth

service: cognito
frameworkVersion: ">=1.14.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  profile: tab-sls
  stage: ${env:SLS_STAGE, self:custom.stageDefault}

custom:
  stageDefault: dev

resources:
  Resources:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
    CognitoUserPoolTabUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: tab-${opt:stage, self:provider.stage}
        AutoVerifiedAttributes:
          - email
        AliasAttributes:
          - email
        MfaConfiguration: "OFF"
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html#cfn-cognito-userpool-schemaattribute-stringattributeconstraints
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
    
    UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: tab-${opt:stage, self:provider.stage}-client
        GenerateSecret: false
        # The time limit, in days, after which the refresh token
        # is no longer valid.
        RefreshTokenValidity: 3650
        UserPoolId: 
          Ref: CognitoUserPoolTabUserPool
        # Used in tests to create and manage users:
        # https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-admin-authentication-flow
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
