
service: lambda
frameworkVersion: "=1.13.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  profile: tab-sls
  stage: dev

functions:
  hearts:
    handler: hearts/hearts.serverlessHandler
    events:
      - http:
          path: hearts/
          method: get
          authorizer:
            name: authorizer_${opt:stage, self:provider.stage}
            arn:  arn:aws:cognito-idp:us-west-2:167811431063:userpool/us-west-2_9MWuEqLeW 
